# Generated by Django 5.1.6 on 2025-03-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0004_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
