# Generated by Django 5.1.6 on 2025-03-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcars', '0005_booking_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
